development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/zendesk_data_collector_development' %>
      options:
        read:
          mode: :primary
        max_pool_size: 5

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST_URI'] || 'mongodb://localhost:27017/zendesk_data_collector_test' %>
      options:
        read:
          mode: :primary
        max_pool_size: 5

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'NOT_SET' %>
      options:
        read:
          mode: :primary
        max_pool_size: 10
