production:
  concurrency: 15
  queues: "default,comments" # Process default queue (incremental) before comments queue
  polling_interval: 1

development:
  concurrency: 5
  queues: "default,comments" # Process default queue (incremental) before comments queue
  polling_interval: 1

test:
  concurrency: 2
  queues: "default,comments" # Process default queue (incremental) before comments queue
  polling_interval: 1
