production:
  concurrency: 15
  queues: "default,metrics,comments" # Process default queue (incremental) first, then metrics (priority 10), then comments (priority 20)
  polling_interval: 1

development:
  concurrency: 5
  queues: "default,metrics,comments" # Process default queue (incremental) first, then metrics (priority 10), then comments (priority 20)
  polling_interval: 1

test:
  concurrency: 2
  queues: "default,metrics,comments" # Process default queue (incremental) first, then metrics (priority 10), then comments (priority 20)
  polling_interval: 1
